const STORAGE_KEY="militaryTimetableDb.v1";
const timeSlots=["๐๘๐๐ - ๑๐๐๐","๑๐๐๐ - ๑๒๐๐","๑๓๐๐ - ๑๕๐๐","๑๕๐๐ - ๑๗๐๐"];
const demoData={courses:[{id:"c1",name:"หลักสูตร ชั้นนายพัน เหล่า ขส.",batch:"รุ่นที่ ๕๗"}],subjects:[{id:"s1",courseId:"c1",name:"นทน.รายงานตัว",totalHours:0},{id:"s2",courseId:"c1",name:"เวลา ผบ.",totalHours:0},{id:"s3",courseId:"c1",name:"ปฐมนิเทศคณิตศาสตร์",totalHours:2},{id:"s4",courseId:"c1",name:"ซักซ้อมพิธีเปิดการศึกษา",totalHours:2},{id:"s5",courseId:"c1",name:"พิธีเปิดการศึกษา",totalHours:2}],teachers:[{id:"t1",name:"พัน.นร.รร.ขส.ขส.ทบ.",rank:""},{id:"t2",name:"กศ.รร.ขส.ขส.ทบ.",rank:""},{id:"t3",name:"ผอ.หลักสูตรฯ, ผช.(๑), ผช.(๒)",rank:""},{id:"t4",name:"ผตก.รร.ขส.ขส.ทบ.",rank:""}],methods:[{id:"m1",name:"ป"},{id:"m2",name:"บ"}],rooms:[{id:"r1",name:"พัน.นร.ฯ"},{id:"r2",name:"ห้องเรียน ๓"},{id:"r3",name:"ห้องเรียน ๑"}],dressCodes:[{id:"d1",name:"ชุดปกติแขนยาว"},{id:"d2",name:"ชุดปกติ"}],schedules:[{id:"sc1",dateText:"วันศุกร์ที่ ๑ พ.ค. ๖๙",studyDate:"2026-05-01",timeSlot:"๐๘๐๐ - ๑๐๐๐",courseId:"c1",subjectId:"s1",hourUsage:"-",teacherId:"t1",methodId:"m1",roomId:"r1",evidence:"รร.ขส.ฯ",dressCode:"ชุดปกติแขนยาว",note:""},{id:"sc2",dateText:"วันศุกร์ที่ ๑ พ.ค. ๖๙",studyDate:"2026-05-01",timeSlot:"๑๐๐๐ - ๑๒๐๐",courseId:"c1",subjectId:"s2",hourUsage:"-",teacherId:"t3",methodId:"m2",roomId:"r2",evidence:"รร.ขส.ฯ",dressCode:"ชุดปกติแขนยาว",note:""},{id:"sc3",dateText:"วันศุกร์ที่ ๑ พ.ค. ๖๙",studyDate:"2026-05-01",timeSlot:"๑๓๐๐ - ๑๕๐๐",courseId:"c1",subjectId:"s3",hourUsage:"๒/๒",teacherId:"",methodId:"m2",roomId:"r2",evidence:"รร.ขส.ฯ",dressCode:"ชุดปกติแขนยาว",note:"สอบ ๑๐ คะแนนโดยอาจารย์คณะกรรมการ รร.ขส.ฯ"}]};
let db=loadDb();
function loadDb(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return structuredClone(demoData);try{return JSON.parse(raw)}catch{return structuredClone(demoData)}}
function saveDb(){localStorage.setItem(STORAGE_KEY,JSON.stringify(db))}
function uid(prefix){return`${prefix}${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`}
function byId(id){return document.getElementById(id)}
function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[char]))}
function findName(collection,id){return db[collection].find(item=>item.id===id)?.name||""}
function setOptions(select,rows,placeholder="เลือกรายการ"){select.innerHTML=`<option value="">${placeholder}</option>`+rows.map(row=>`<option value="${row.id}">${escapeHtml(row.name)}</option>`).join("")}
function parseUsedHours(hourUsage){const arabic=String(hourUsage||"").replace(/[๐-๙]/g,digit=>"๐๑๒๓๔๕๖๗๘๙".indexOf(digit));const match=arabic.match(/(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)/);return match?Number(match[1]):0}
function init(){byId("loginForm").addEventListener("submit",handleLogin);byId("logoutBtn").addEventListener("click",()=>{byId("appView").classList.add("hidden");byId("loginView").classList.remove("hidden")});document.querySelectorAll(".nav-item").forEach(button=>button.addEventListener("click",()=>switchView(button.dataset.view)));byId("resetDemoBtn").addEventListener("click",()=>{if(!confirm("ต้องการคืนค่าข้อมูลตัวอย่างหรือไม่"))return;db=structuredClone(demoData);saveDb();renderAll()});byId("exportBtn").addEventListener("click",exportJson);byId("exportScheduleBtn").addEventListener("click",exportSchedule);byId("scheduleSearch").addEventListener("input",renderSchedules);byId("clearScheduleForm").addEventListener("click",clearScheduleForm);byId("deleteScheduleBtn").addEventListener("click",deleteCurrentSchedule);byId("scheduleForm").addEventListener("submit",saveSchedule);byId("courseForm").addEventListener("submit",saveCourse);byId("subjectForm").addEventListener("submit",saveSubject);byId("teacherForm").addEventListener("submit",saveTeacher);byId("lookupForm").addEventListener("submit",saveLookup);byId("lookupType").addEventListener("change",renderLookups);byId("timeSlot").innerHTML=timeSlots.map(slot=>`<option value="${slot}">${slot}</option>`).join("");byId("exportReferenceDate").value=new Date().toISOString().slice(0,10);renderAll()}
function handleLogin(event){event.preventDefault();if(byId("username").value.trim()!=="admin"||byId("password").value.trim()!=="1234"){alert("ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง");return}byId("loginView").classList.add("hidden");byId("appView").classList.remove("hidden")}
function switchView(viewId){document.querySelectorAll(".nav-item").forEach(button=>button.classList.toggle("active",button.dataset.view===viewId));document.querySelectorAll(".view").forEach(view=>view.classList.toggle("active-view",view.id===viewId));byId("pageTitle").textContent={dashboard:"Dashboard",schedule:"ตารางเรียน",registry:"ทะเบียนคุม",masterData:"ข้อมูลพื้นฐาน",database:"ฐานข้อมูล"}[viewId]}
function renderAll(){renderOptions();renderDashboard();renderSchedules();renderCourses();renderSubjects();renderTeachers();renderLookups()}
function renderOptions(){setOptions(byId("courseId"),db.courses,"เลือกหลักสูตร");setOptions(byId("subjectCourseId"),db.courses,"เลือกหลักสูตร");setOptions(byId("subjectId"),db.subjects,"เลือกวิชา");setOptions(byId("teacherId"),db.teachers,"เลือกผู้สอน");setOptions(byId("methodId"),db.methods,"เลือกวิธีสอน");setOptions(byId("roomId"),db.rooms,"เลือกสถานที่");setOptions(byId("dressCode"),db.dressCodes,"เลือกการแต่งกาย")}
function renderDashboard(){byId("metricSchedules").textContent=db.schedules.length;byId("metricCourses").textContent=db.courses.length;byId("metricSubjects").textContent=db.subjects.length;byId("metricTeachers").textContent=db.teachers.length;byId("subjectProgress").innerHTML=db.subjects.map(subject=>{const used=db.schedules.filter(row=>row.subjectId===subject.id).reduce((sum,row)=>sum+parseUsedHours(row.hourUsage),0);const total=Number(subject.totalHours)||used||0;const pct=total?Math.min(100,Math.round(used/total*100)):0;return`<div class="progress-row"><div class="progress-meta"><strong>${escapeHtml(subject.name)}</strong><span>${used}/${total} ชม.</span></div><div class="bar"><span style="width:${pct}%"></span></div></div>`}).join("")||"<p class='muted'>ยังไม่มีข้อมูลวิชา</p>";byId("latestSchedule").innerHTML=db.schedules.slice(-5).reverse().map(row=>`<div class="compact-item"><div><strong>${escapeHtml(findName("subjects",row.subjectId))}</strong><small>${escapeHtml(row.dateText)} · ${escapeHtml(row.timeSlot)}</small></div><button class="tiny-button" data-edit-schedule="${row.id}">แก้ไข</button></div>`).join("")||"<p class='muted'>ยังไม่มีรายการตารางเรียน</p>";bindScheduleButtons()}
function renderSchedules(){const query=byId("scheduleSearch").value.trim().toLowerCase();const rows=db.schedules.filter(row=>[row.dateText,row.studyDate,row.timeSlot,findName("subjects",row.subjectId),findName("teachers",row.teacherId),findName("methods",row.methodId),findName("rooms",row.roomId),row.evidence,row.dressCode,row.note].join(" ").toLowerCase().includes(query));byId("scheduleTable").innerHTML=rows.map(row=>`<tr><td>${escapeHtml(row.dateText)}</td><td>${escapeHtml(row.timeSlot)}</td><td>${escapeHtml(findName("subjects",row.subjectId))}</td><td>${escapeHtml(row.hourUsage)}</td><td>${escapeHtml(findName("teachers",row.teacherId))}</td><td>${escapeHtml(findName("methods",row.methodId))}</td><td>${escapeHtml(findName("rooms",row.roomId))}</td><td>${escapeHtml(row.evidence)}</td><td>${escapeHtml(row.dressCode)}</td><td>${escapeHtml(row.note)}</td><td><button class="tiny-button" data-edit-schedule="${row.id}">แก้ไข</button></td></tr>`).join("")||`<tr><td colspan="11">ไม่พบข้อมูล</td></tr>`;bindScheduleButtons()}
function bindScheduleButtons(){document.querySelectorAll("[data-edit-schedule]").forEach(button=>button.addEventListener("click",()=>editSchedule(button.dataset.editSchedule)))}
function saveSchedule(event){event.preventDefault();const id=byId("scheduleId").value||uid("sc");const row={id,dateText:byId("scheduleDate").value.trim(),studyDate:byId("studyDate").value,timeSlot:byId("timeSlot").value,courseId:byId("courseId").value,subjectId:byId("subjectId").value,hourUsage:byId("hourUsage").value.trim(),teacherId:byId("teacherId").value,methodId:byId("methodId").value,roomId:byId("roomId").value,evidence:byId("evidence").value.trim(),dressCode:byId("dressCode").selectedOptions[0]?.textContent||"",note:byId("note").value.trim()};const index=db.schedules.findIndex(item=>item.id===id);if(index>=0)db.schedules[index]=row;else db.schedules.push(row);saveDb();clearScheduleForm();renderAll()}
function editSchedule(id){const row=db.schedules.find(item=>item.id===id);if(!row)return;switchView("schedule");byId("scheduleId").value=row.id;byId("scheduleDate").value=row.dateText;byId("studyDate").value=row.studyDate||"";byId("timeSlot").value=row.timeSlot;byId("courseId").value=row.courseId;byId("subjectId").value=row.subjectId;byId("hourUsage").value=row.hourUsage;byId("teacherId").value=row.teacherId;byId("methodId").value=row.methodId;byId("roomId").value=row.roomId;byId("evidence").value=row.evidence;byId("dressCode").value=db.dressCodes.find(item=>item.name===row.dressCode)?.id||"";byId("note").value=row.note;byId("deleteScheduleBtn").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
function clearScheduleForm(){byId("scheduleForm").reset();byId("scheduleId").value="";byId("deleteScheduleBtn").classList.add("hidden")}
function deleteCurrentSchedule(){const id=byId("scheduleId").value;if(!id||!confirm("ต้องการลบรายการตารางเรียนนี้หรือไม่"))return;db.schedules=db.schedules.filter(item=>item.id!==id);saveDb();clearScheduleForm();renderAll()}
function upsert(collection,row){const index=db[collection].findIndex(item=>item.id===row.id);if(index>=0)db[collection][index]=row;else db[collection].push(row);saveDb()}
function saveCourse(event){event.preventDefault();upsert("courses",{id:byId("courseEditId").value||uid("c"),name:byId("courseName").value.trim(),batch:byId("courseBatch").value.trim()});byId("courseForm").reset();byId("courseEditId").value="";renderAll()}
function saveSubject(event){event.preventDefault();upsert("subjects",{id:byId("subjectEditId").value||uid("s"),courseId:byId("subjectCourseId").value,name:byId("subjectName").value.trim(),totalHours:Number(byId("subjectHours").value||0)});byId("subjectForm").reset();byId("subjectEditId").value="";renderAll()}
function saveTeacher(event){event.preventDefault();upsert("teachers",{id:byId("teacherEditId").value||uid("t"),name:byId("teacherName").value.trim(),rank:byId("teacherRank").value.trim()});byId("teacherForm").reset();byId("teacherEditId").value="";renderAll()}
function saveLookup(event){event.preventDefault();const type=byId("lookupType").value;db[type].push({id:uid(type.slice(0,1)),name:byId("lookupName").value.trim()});saveDb();byId("lookupName").value="";renderAll()}
function removeItem(collection,id){if(!confirm("ต้องการลบข้อมูลนี้หรือไม่"))return;db[collection]=db[collection].filter(item=>item.id!==id);saveDb();renderAll()}
function renderCourses(){byId("courseList").innerHTML=db.courses.map(row=>recordHtml(row.name,row.batch||"-",`data-edit-course="${row.id}"`,`data-delete-course="${row.id}"`)).join("");bindRecordButtons("course","courses")}
function renderSubjects(){byId("subjectList").innerHTML=db.subjects.map(row=>recordHtml(row.name,`${findName("courses",row.courseId)} · ${row.totalHours||0} ชม.`,`data-edit-subject="${row.id}"`,`data-delete-subject="${row.id}"`)).join("");bindRecordButtons("subject","subjects")}
function renderTeachers(){byId("teacherList").innerHTML=db.teachers.map(row=>recordHtml(row.name,row.rank||"-",`data-edit-teacher="${row.id}"`,`data-delete-teacher="${row.id}"`)).join("");bindRecordButtons("teacher","teachers")}
function recordHtml(title,subtitle,editAttr,deleteAttr){return`<div class="record-item"><div><strong>${escapeHtml(title)}</strong><small>${escapeHtml(subtitle)}</small></div><div class="item-actions"><button class="tiny-button" ${editAttr}>แก้ไข</button><button class="tiny-button" ${deleteAttr}>ลบ</button></div></div>`}
function bindRecordButtons(type,collection){document.querySelectorAll(`[data-delete-${type}]`).forEach(button=>button.addEventListener("click",()=>removeItem(collection,button.dataset[`delete${cap(type)}`])));document.querySelectorAll(`[data-edit-${type}]`).forEach(button=>button.addEventListener("click",()=>editRecord(type,button.dataset[`edit${cap(type)}`])))}
function editRecord(type,id){if(type==="course"){const row=db.courses.find(item=>item.id===id);byId("courseEditId").value=row.id;byId("courseName").value=row.name;byId("courseBatch").value=row.batch||""}if(type==="subject"){const row=db.subjects.find(item=>item.id===id);byId("subjectEditId").value=row.id;byId("subjectCourseId").value=row.courseId;byId("subjectName").value=row.name;byId("subjectHours").value=row.totalHours||0}if(type==="teacher"){const row=db.teachers.find(item=>item.id===id);byId("teacherEditId").value=row.id;byId("teacherName").value=row.name;byId("teacherRank").value=row.rank||""}}
function cap(value){return value.charAt(0).toUpperCase()+value.slice(1)}
function renderLookups(){const type=byId("lookupType").value;byId("lookupList").innerHTML=db[type].map(row=>`<div class="record-item"><div><strong>${escapeHtml(row.name)}</strong></div><div class="item-actions"><button class="tiny-button" data-delete-lookup="${row.id}">ลบ</button></div></div>`).join("");document.querySelectorAll("[data-delete-lookup]").forEach(button=>button.addEventListener("click",()=>removeItem(type,button.dataset.deleteLookup)))}
function exportJson(){downloadBlob(JSON.stringify(db,null,2),"timetable-data.json","application/json")}
function exportSchedule(){const period=byId("exportPeriod").value;const format=byId("exportFormat").value;const referenceDate=byId("exportReferenceDate").value;const rows=getRowsForExport(period,referenceDate);if(!rows.length){alert("ไม่พบข้อมูลในช่วงวันที่ที่เลือก");return}if(format==="excel")exportScheduleExcel(rows,period,referenceDate);else exportSchedulePdf(rows,period,referenceDate)}
function getRowsForExport(period,referenceDate){if(!referenceDate)return[...db.schedules];const reference=parseLocalDate(referenceDate);const start=period==="week"?startOfWeek(reference):new Date(reference.getFullYear(),reference.getMonth(),1);const end=period==="week"?addDays(start,6):new Date(reference.getFullYear(),reference.getMonth()+1,0,23,59,59,999);return db.schedules.filter(row=>{if(!row.studyDate)return true;const date=parseLocalDate(row.studyDate);return date>=start&&date<=end}).sort((a,b)=>`${a.studyDate||""} ${a.timeSlot}`.localeCompare(`${b.studyDate||""} ${b.timeSlot}`))}
function exportRows(rows){return rows.map(row=>({"วัน , เดือน , ปี":row.dateText,"วันที่จริง":row.studyDate||"","เวลา":row.timeSlot,"วิชา":findName("subjects",row.subjectId),"ชม.ที่ใช้ หมดไป/ชม.ทั้งหมด":row.hourUsage,"ผู้สอน":findName("teachers",row.teacherId),"วิธีสอน":findName("methods",row.methodId),"สถานที่":findName("rooms",row.roomId),"หลักฐาน":row.evidence,"การแต่งกาย":row.dressCode,"หมายเหตุ":row.note}))}
function exportTitle(period,referenceDate){const label=period==="week"?"รายสัปดาห์":"รายเดือน";return`ตารางเรียน${label}${referenceDate?` ${referenceDate}`:""}`}
function exportScheduleExcel(rows,period,referenceDate){const data=exportRows(rows);const headers=Object.keys(data[0]);const html=`<html><head><meta charset="utf-8"></head><body><table border="1"><thead><tr>${headers.map(header=>`<th>${escapeHtml(header)}</th>`).join("")}</tr></thead><tbody>${data.map(row=>`<tr>${headers.map(header=>`<td>${escapeHtml(row[header])}</td>`).join("")}</tr>`).join("")}</tbody></table></body></html>`;downloadBlob(html,`${exportTitle(period,referenceDate)}.xls`,"application/vnd.ms-excel;charset=utf-8")}
function exportSchedulePdf(rows,period,referenceDate){const data=exportRows(rows);const headers=Object.keys(data[0]);const printWindow=window.open("","_blank");if(!printWindow){alert("เบราว์เซอร์บล็อกหน้าต่างใหม่ กรุณาอนุญาต popup ก่อน Export PDF");return}printWindow.document.write(`<!doctype html><html lang="th"><head><meta charset="utf-8"><title>${escapeHtml(exportTitle(period,referenceDate))}</title><style>@page{size:A4 landscape;margin:12mm}body{font-family:"Segoe UI",Tahoma,sans-serif;color:#172033}h1{font-size:20px;margin:0 0 12px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #9aa7b7;padding:6px;vertical-align:top}th{background:#eef4ff}</style></head><body><h1>${escapeHtml(exportTitle(period,referenceDate))}</h1><table><thead><tr>${headers.map(header=>`<th>${escapeHtml(header)}</th>`).join("")}</tr></thead><tbody>${data.map(row=>`<tr>${headers.map(header=>`<td>${escapeHtml(row[header])}</td>`).join("")}</tr>`).join("")}</tbody></table><script>window.onload=()=>{window.print()};<\/script></body></html>`);printWindow.document.close()}
function downloadBlob(content,fileName,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=fileName;link.click();URL.revokeObjectURL(url)}
function parseLocalDate(value){const[year,month,day]=value.split("-").map(Number);return new Date(year,month-1,day)}
function startOfWeek(date){const start=new Date(date);const day=start.getDay()||7;start.setDate(start.getDate()-day+1);start.setHours(0,0,0,0);return start}
function addDays(date,days){const result=new Date(date);result.setDate(result.getDate()+days);result.setHours(23,59,59,999);return result}
init();
